 const PARTIAL_MATCH_ENUM = "PARTIAL_MATCH";
 const EXACT_MATCH_ENUM = "EXACT_MATCH";
 const METHOD_TYPES_ENUM = {
   GET: "GET",
   POST: "POST",
   PUT: "PUT",
   DELETE: "DELETE",
 };

 module.exports = {
   PARTIAL_MATCH_ENUM,
   EXACT_MATCH_ENUM,
   METHOD_TYPES_ENUM,
 }